services:
  url-db:
    image: postgres:17.4-bookworm
    container_name: url-db
    hostname: ${POSTGRES_HOST}
    networks:
      - backend
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
  
  url-cache:
    image: redis:7.4-bookworm
    container_name: url-cache
    hostname: ${REDIS_HOST}
    networks:
      - backend
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - DB=${REDIS_DB}

  migrator:
    depends_on:
      - url-db
    build: 
      context: .
      args:
        MIGRATIONS_PATH: "migrations"
    command: ["./migrator", "--migrations-path=migrations"]
  
  url-shortener:
    depends_on:
      - url-db
      - migrator
    build:
      context: .
      args:
        CONFIG_PATH: "configs/dev.yaml"
    command: ["./url-shortener", "--config-path=config.yaml"]

# TODO: add volumes
  
networks:
  backend:
    driver: bridge
